---
- name: Download data
  hosts: workvm
  remote_user: saasi
  become_method: sudo
  become_user: root
  become: true

  tasks:
  - name: "Add my key to authorized_keys"
    authorized_key:
      user: saasi
      state: present
      key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
  - name: export docker logs
    shell: docker-compose -f docker-compose.yml -f docker-compose.override.yml logs > /app/workvm/Application3/Monitor/data/docker.log
    args:
      chdir: /app/workvm/Application3/
  - name: download monitor data
#    become: false
    synchronize: 
      src: /app/workvm/Application3/Monitor/data 
      dest: /root/downloaded/data-{{ inventory_hostname }} 
      mode: pull
  - name: "remove my key from authorized_keys"
    authorized_key:
      user: saasi
      state: absent
      key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"

#  - name: find iiles
#    shell: (cd /app/workvm/Application3/Monitor/data; find . -maxdepth 1 -type f) | cut -d'/' -f2
#    register: files_to_copy
#  - debug:
#      var: files_to_copy.stdout_lines
#  - name: download files
#    fetch: src=/app/workvm/Application3/Monitor/data/{{ item }} dest=/root/downloaded/ validate_checksum=yes #data-{{ inventory_hostname }}
#    with_items: files_to_copy.stdout_lines
    #validate_checksum: yes
