---
- name: Generate Git Deploy keys, and print public key
  hosts: all
  remote_user: saasi
  become_method: sudo
  become_user: root

  tasks:
  - name: check if ssh key exists
    stat: path=/root/.ssh/id_rsa
    register: ssh_key
  - name: ensure ssh key generated
    shell: ssh-keygen -t rsa -f /root/.ssh/id_rsa -N ''
    when: ssh_key.stat.exists == False
  - name: print public key
    shell: cat /root/.ssh/id_rsa.pub
