---
- name: Pull latest code, and run microservices
  hosts: workvm
  remote_user: saasi
  become_method: sudo
  become_user: root
  become: true

  tasks:
  - name: create dir
    file: path=/app state=directory
  - name: checkout code
    git:
      repo: 'git@github.com:ztl8702/saasi-experiment.git'
      dest: /app
      version: deploy
      force: true
      accept_hostkey: true
  - name: add permissions
    shell: chmod +x /app/workvm/Application3/run.sh && chmod -R o+r /app && chmod -R o+x /app && chmod -R o+w /app
  - name: run microservices
    shell: ./run.sh
    args:
      chdir: /app/workvm/Application3/
  - name: run Monitor
    shell: dotnet restore && dotnet run &
    become: false
    args:
      chdir:  /app/workvm/Application3/Monitor/
  - name: run DM
    shell: dotnet restore && dotnet run &
    args:
      chdir: /app/workvm/DM/DM/
    become: false
