---
- name: Pull latest code, and run microservices
  hosts: all
  remote_user: saasi
  become_method: sudo
  become_user: root
  become: true

  tasks:
  - name: create dir
    file: path=/app state=directory
  - name: checkout code
    git:
      repo: 'git@github.com:ztl8702/saasi-experiment.git'
      dest: /app
      version: deploy
      force: true
      accept_hostkey: true
  - name: add permissions
    shell: chmod +x /app/workvm/Application3/run.sh
  - name: run microservices
    shell: ./run.sh
    args:
      chdir: /app/workvm/Application3/
  - name: run DM
    shell: dotnet run /app/workvm/Application3/Monitor/Monitor.csproj
